//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatEstado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatEstado()
        {
            this.TblAsistenciasAsambaleas = new HashSet<TblAsistenciasAsambalea>();
            this.CatBusquedas = new HashSet<CatBusqueda>();
            this.CatPermisos = new HashSet<CatPermiso>();
            this.CatPersonas = new HashSet<CatPersona>();
            this.Tbl_U_Roles = new HashSet<Tbl_U_Roles>();
            this.TblBitacoraBusquedaUsuarios = new HashSet<TblBitacoraBusquedaUsuario>();
            this.TblModulos = new HashSet<TblModulo>();
            this.TblPermisosUsuarios = new HashSet<TblPermisosUsuario>();
            this.TblPersonas = new HashSet<TblPersona>();
            this.TblRoles = new HashSet<TblRole>();
            this.TblSesions = new HashSet<TblSesion>();
            this.TblSubModulos = new HashSet<TblSubModulo>();
            this.TblUsuarios = new HashSet<TblUsuario>();
            this.TblUsuarios_Coordinador = new HashSet<TblUsuarios_Coordinador>();
            this.CatImagenesIntranets = new HashSet<CatImagenesIntranet>();
            this.CatJerarquias = new HashSet<CatJerarquia>();
            this.CatOrigens = new HashSet<CatOrigen>();
            this.TblBibliotecas = new HashSet<TblBiblioteca>();
            this.tblpremoras = new HashSet<tblpremora>();
            this.TblCarteraCreditoes = new HashSet<TblCarteraCredito>();
            this.TblResumenSaldoes = new HashSet<TblResumenSaldo>();
            this.TblDeclaracionSaluds = new HashSet<TblDeclaracionSalud>();
            this.CatDestinatariosCorreos = new HashSet<CatDestinatariosCorreo>();
            this.CatSistemasCorreos = new HashSet<CatSistemasCorreo>();
            this.TblSistemasCorreosDestinatariosCorreos = new HashSet<TblSistemasCorreosDestinatariosCorreo>();
            this.TblConvivioImagenes = new HashSet<TblConvivioImagene>();
            this.TblDirectorios = new HashSet<TblDirectorio>();
            this.TblDirectoriosAgencias = new HashSet<TblDirectoriosAgencia>();
            this.CatClasificacionFacturas = new HashSet<CatClasificacionFactura>();
            this.CatColaboradores = new HashSet<CatColaboradore>();
            this.CatDepartamentosRepublicas = new HashSet<CatDepartamentosRepublica>();
            this.CatDepartamentosTrabajoes = new HashSet<CatDepartamentosTrabajo>();
            this.CatEstadoCivils = new HashSet<CatEstadoCivil>();
            this.CatBancos = new HashSet<CatBanco>();
            this.CatDestinatariosCorreos1 = new HashSet<CatDestinatariosCorreo1>();
            this.CatDestinatariosSms = new HashSet<CatDestinatariosSm>();
            this.CatEstadosLoginRches = new HashSet<CatEstadosLoginRch>();
            this.CatEstadoSolicitudes = new HashSet<CatEstadoSolicitude>();
            this.CatEstadosRrhhs = new HashSet<CatEstadosRrhh>();
            this.CatEstadosViaticos = new HashSet<CatEstadosViatico>();
            this.CatHorarioServicios = new HashSet<CatHorarioServicio>();
            this.CatIconos = new HashSet<CatIcono>();
            this.CatLugares = new HashSet<CatLugare>();
            this.CatOpciones = new HashSet<CatOpcione>();
            this.CatOpcionesVehiculos = new HashSet<CatOpcionesVehiculo>();
            this.CatPromociones = new HashSet<CatPromocione>();
            this.CatProveedoresCooitzas = new HashSet<CatProveedoresCooitza>();
            this.CatProveedoresExternos = new HashSet<CatProveedoresExterno>();
            this.CatPuestos = new HashSet<CatPuesto>();
            this.CatPuntos = new HashSet<CatPunto>();
            this.CatRegiones = new HashSet<CatRegione>();
            this.CatRubros = new HashSet<CatRubro>();
            this.CatSerieFacturas = new HashSet<CatSerieFactura>();
            this.CatServiciosMonitors = new HashSet<CatServiciosMonitor>();
            this.CatSexoes = new HashSet<CatSexo>();
            this.CatTblUsuariosXTblSistemas = new HashSet<CatTblUsuariosXTblSistema>();
            this.CatTipificacionProductos = new HashSet<CatTipificacionProducto>();
            this.CatTipoAnticipoes = new HashSet<CatTipoAnticipo>();
            this.CatTipoInstituciones = new HashSet<CatTipoInstitucione>();
            this.CatTipoPlacas = new HashSet<CatTipoPlaca>();
            this.CatTiposCuentas = new HashSet<CatTiposCuenta>();
            this.CatTiposEmpresasProveedores = new HashSet<CatTiposEmpresasProveedore>();
            this.CatTiposMedicions = new HashSet<CatTiposMedicion>();
            this.CatTiposMonedas = new HashSet<CatTiposMoneda>();
            this.CatTiposMovimientos = new HashSet<CatTiposMovimiento>();
            this.CatTipoSolicitudes = new HashSet<CatTipoSolicitude>();
            this.CatTiposProveedores = new HashSet<CatTiposProveedore>();
            this.CatTipoTransacciones = new HashSet<CatTipoTransaccione>();
            this.CatTipoUbicaciones = new HashSet<CatTipoUbicacione>();
            this.CatUbicaciones = new HashSet<CatUbicacione>();
            this.constanciasLaborales = new HashSet<constanciasLaborale>();
            this.MunicipiosRepublicas = new HashSet<MunicipiosRepublica>();
            this.Tbl_Cc_Rubros = new HashSet<Tbl_Cc_Rubros>();
            this.TblAfiliaciones = new HashSet<TblAfiliacione>();
            this.TblAgencias = new HashSet<TblAgencia>();
            this.TblCaracterisitcasGrabacions = new HashSet<TblCaracterisitcasGrabacion>();
            this.TblCertificacionesTecnicos = new HashSet<TblCertificacionesTecnico>();
            this.TblCierresProductos = new HashSet<TblCierresProducto>();
            this.TblConfiguracionesRches = new HashSet<TblConfiguracionesRch>();
            this.TblConvivios = new HashSet<TblConvivio>();
            this.TblDepositos = new HashSet<TblDeposito>();
            this.TblDestinos = new HashSet<TblDestino>();
            this.TblEmpleadosMetas = new HashSet<TblEmpleadosMeta>();
            this.TblEstado_Solicitudes = new HashSet<TblEstado_Solicitudes>();
            this.TblFacturas = new HashSet<TblFactura>();
            this.TblFacturasXcatRubros = new HashSet<TblFacturasXcatRubro>();
            this.TblGirasTecnicos = new HashSet<TblGirasTecnico>();
            this.TblGruposAgencias = new HashSet<TblGruposAgencia>();
            this.TblHistoricos = new HashSet<TblHistorico>();
            this.TblMigracions = new HashSet<TblMigracion>();
            this.TblMonitorGrabacions = new HashSet<TblMonitorGrabacion>();
            this.TblMonitorGrabacions1 = new HashSet<TblMonitorGrabacion>();
            this.TblPeriodos = new HashSet<TblPeriodo>();
            this.TblProductosCooitzas = new HashSet<TblProductosCooitza>();
            this.TblProveedores = new HashSet<TblProveedore>();
            this.TblSistemas = new HashSet<TblSistema>();
            this.TblSolicitudes = new HashSet<TblSolicitude>();
            this.TblSolicitudesCooitzas = new HashSet<TblSolicitudesCooitza>();
            this.TblSolicitudesMoviemientos = new HashSet<TblSolicitudesMoviemiento>();
            this.TblSolicitudesMovimientosDetalles = new HashSet<TblSolicitudesMovimientosDetalle>();
            this.TblSucrusalesProductosCooitzas = new HashSet<TblSucrusalesProductosCooitza>();
            this.TblUsuarios1 = new HashSet<TblUsuarios1>();
            this.TblVehiculos = new HashSet<TblVehiculo>();
        }
    
        public long idCatEstados { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idCatUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatUsuarioModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsistenciasAsambalea> TblAsistenciasAsambaleas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatBusqueda> CatBusquedas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatPermiso> CatPermisos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatPersona> CatPersonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_U_Roles> Tbl_U_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBitacoraBusquedaUsuario> TblBitacoraBusquedaUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblModulo> TblModulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPermisosUsuario> TblPermisosUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPersona> TblPersonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRole> TblRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSesion> TblSesions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubModulo> TblSubModulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUsuario> TblUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUsuarios_Coordinador> TblUsuarios_Coordinador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatImagenesIntranet> CatImagenesIntranets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatJerarquia> CatJerarquias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatOrigen> CatOrigens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBiblioteca> TblBibliotecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpremora> tblpremoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCarteraCredito> TblCarteraCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblResumenSaldo> TblResumenSaldoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatDestinatariosCorreo> CatDestinatariosCorreos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatSistemasCorreo> CatSistemasCorreos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSistemasCorreosDestinatariosCorreo> TblSistemasCorreosDestinatariosCorreos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblConvivioImagene> TblConvivioImagenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDirectorio> TblDirectorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDirectoriosAgencia> TblDirectoriosAgencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatClasificacionFactura> CatClasificacionFacturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatColaboradore> CatColaboradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatDepartamentosRepublica> CatDepartamentosRepublicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatDepartamentosTrabajo> CatDepartamentosTrabajoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatEstadoCivil> CatEstadoCivils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatBanco> CatBancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatDestinatariosCorreo1> CatDestinatariosCorreos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatDestinatariosSm> CatDestinatariosSms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatEstadosLoginRch> CatEstadosLoginRches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatEstadoSolicitude> CatEstadoSolicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatEstadosRrhh> CatEstadosRrhhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatEstadosViatico> CatEstadosViaticos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatHorarioServicio> CatHorarioServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatIcono> CatIconos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatLugare> CatLugares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatOpcione> CatOpciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatOpcionesVehiculo> CatOpcionesVehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatPromocione> CatPromociones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatProveedoresCooitza> CatProveedoresCooitzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatProveedoresExterno> CatProveedoresExternos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatPuesto> CatPuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatPunto> CatPuntos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatRegione> CatRegiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatRubro> CatRubros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatSerieFactura> CatSerieFacturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatServiciosMonitor> CatServiciosMonitors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatSexo> CatSexoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTblUsuariosXTblSistema> CatTblUsuariosXTblSistemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipificacionProducto> CatTipificacionProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipoAnticipo> CatTipoAnticipoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipoInstitucione> CatTipoInstituciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipoPlaca> CatTipoPlacas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposCuenta> CatTiposCuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposEmpresasProveedore> CatTiposEmpresasProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposMedicion> CatTiposMedicions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposMoneda> CatTiposMonedas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposMovimiento> CatTiposMovimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipoSolicitude> CatTipoSolicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTiposProveedore> CatTiposProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipoTransaccione> CatTipoTransacciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTipoUbicacione> CatTipoUbicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatUbicacione> CatUbicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<constanciasLaborale> constanciasLaborales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MunicipiosRepublica> MunicipiosRepublicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Cc_Rubros> Tbl_Cc_Rubros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAfiliacione> TblAfiliaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAgencia> TblAgencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCaracterisitcasGrabacion> TblCaracterisitcasGrabacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCertificacionesTecnico> TblCertificacionesTecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCierresProducto> TblCierresProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblConfiguracionesRch> TblConfiguracionesRches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblConvivio> TblConvivios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeposito> TblDepositos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDestino> TblDestinos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpleadosMeta> TblEmpleadosMetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEstado_Solicitudes> TblEstado_Solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFactura> TblFacturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFacturasXcatRubro> TblFacturasXcatRubros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGirasTecnico> TblGirasTecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGruposAgencia> TblGruposAgencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHistorico> TblHistoricos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMigracion> TblMigracions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMonitorGrabacion> TblMonitorGrabacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMonitorGrabacion> TblMonitorGrabacions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPeriodo> TblPeriodos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductosCooitza> TblProductosCooitzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProveedore> TblProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSistema> TblSistemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitude> TblSolicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudesCooitza> TblSolicitudesCooitzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudesMoviemiento> TblSolicitudesMoviemientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudesMovimientosDetalle> TblSolicitudesMovimientosDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSucrusalesProductosCooitza> TblSucrusalesProductosCooitzas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUsuarios1> TblUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVehiculo> TblVehiculos { get; set; }
    }
}
