//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatOpcionesAsamblea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatOpcionesAsamblea()
        {
            this.TblAsistenciasAsambaleas = new HashSet<TblAsistenciasAsambalea>();
            this.TblAsistenciasAsambaleas1 = new HashSet<TblAsistenciasAsambalea>();
            this.TblAsistenciasAsambaleas2 = new HashSet<TblAsistenciasAsambalea>();
            this.TblAsistenciasAsambaleas3 = new HashSet<TblAsistenciasAsambalea>();
            this.TblAsistenciasAsambaleas4 = new HashSet<TblAsistenciasAsambalea>();
        }
    
        public long idCatOpcionesAsambleas { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsistenciasAsambalea> TblAsistenciasAsambaleas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsistenciasAsambalea> TblAsistenciasAsambaleas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsistenciasAsambalea> TblAsistenciasAsambaleas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsistenciasAsambalea> TblAsistenciasAsambaleas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsistenciasAsambalea> TblAsistenciasAsambaleas4 { get; set; }
    }
}
