//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatOpcionesChn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatOpcionesChn()
        {
            this.TblDeclaracionSaludlgs = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs1 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs2 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs3 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs4 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs5 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs6 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs7 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs8 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs9 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs10 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs11 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs12 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs13 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs14 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs15 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs16 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs17 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs18 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs19 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs20 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs21 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs22 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs23 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs24 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs25 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs26 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs27 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs28 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs29 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs30 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs31 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs32 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs33 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs34 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs35 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs36 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs37 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs38 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs39 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs40 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs41 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs42 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs43 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs44 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs45 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs46 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs47 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs48 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs49 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs50 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs51 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs52 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs53 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludlgs54 = new HashSet<TblDeclaracionSaludlg>();
            this.TblDeclaracionSaludchnlgs = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs1 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs2 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs3 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs4 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs5 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs6 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs7 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs8 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs9 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs10 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs11 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs12 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs13 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs14 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs15 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs16 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs17 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs18 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs19 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs20 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs21 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs22 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs23 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs24 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs25 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs26 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs27 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs28 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs29 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs30 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs31 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs32 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs33 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs34 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs35 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs36 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs37 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs38 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs39 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs40 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs41 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs42 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs43 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs44 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs45 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs46 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs47 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs48 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs49 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs50 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs51 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs52 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaludchnlgs53 = new HashSet<TblDeclaracionSaludchnlg>();
            this.TblDeclaracionSaluds = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds1 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds2 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds3 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds4 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds5 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds6 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds7 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds8 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds9 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds10 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds11 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds12 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds13 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds14 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds15 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds16 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds17 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds18 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds19 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds20 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds21 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds22 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds23 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds24 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds25 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds26 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds27 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds28 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds29 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds30 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds31 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds32 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds33 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds34 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds35 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds36 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds37 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds38 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds39 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds40 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds41 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds42 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds43 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds44 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds45 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds46 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds47 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds48 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds49 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds50 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds51 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds52 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds53 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds54 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds55 = new HashSet<TblDeclaracionSalud>();
            this.TblDeclaracionSaluds56 = new HashSet<TblDeclaracionSalud>();
        }
    
        public long idCatOpcionesChn { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs31 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs32 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs33 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs34 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs35 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs36 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs37 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs38 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs39 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs41 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs42 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs43 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs44 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs45 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs46 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs47 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs48 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs49 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs50 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs52 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs53 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludlg> TblDeclaracionSaludlgs54 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs31 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs32 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs33 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs34 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs35 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs36 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs37 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs38 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs39 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs41 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs42 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs43 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs44 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs45 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs46 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs47 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs48 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs49 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs50 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs52 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSaludchnlg> TblDeclaracionSaludchnlgs53 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds24 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds25 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds26 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds27 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds28 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds29 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds31 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds32 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds33 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds34 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds35 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds36 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds37 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds38 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds39 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds41 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds42 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds43 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds44 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds45 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds46 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds47 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds48 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds49 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds50 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds52 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds53 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds54 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds55 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDeclaracionSalud> TblDeclaracionSaluds56 { get; set; }
    }
}
