//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatProveedoresPagos1
    {
        public long idCatProveedoresPagos { get; set; }
        public string nombre { get; set; }
        public string razonSocial { get; set; }
        public Nullable<long> idCatDescripcionesProveedores { get; set; }
        public string direccion { get; set; }
        public string nombreContacto { get; set; }
        public string telefono { get; set; }
        public Nullable<long> idCatTiposCredito { get; set; }
        public string correo { get; set; }
        public Nullable<long> idCatCuentasProveedores { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<long> idTblUsuarioAlta { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
    
        public virtual CatCuentasProveedore CatCuentasProveedore { get; set; }
        public virtual CatDescripcionesProveedore CatDescripcionesProveedore { get; set; }
    }
}
