//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatProveedoresCooitza
    {
        public long idCatProveedoresCooitzas { get; set; }
        public string nombre { get; set; }
        public string nit { get; set; }
        public Nullable<long> idTblUsuariosAlta { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> idCatBancos { get; set; }
        public Nullable<long> idCatTiposCuentas { get; set; }
        public string numeroCuenta { get; set; }
        public string nombreEmpresa { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual CatEstado CatEstado { get; set; }
    }
}
