//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatPermiso
    {
        public long idCatPermisos { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> idTblRoles { get; set; }
        public Nullable<long> idTblModulos { get; set; }
        public Nullable<long> idTblSubModulos { get; set; }
        public Nullable<int> borrar { get; set; }
        public Nullable<int> actualizar { get; set; }
        public Nullable<int> Ver { get; set; }
        public Nullable<int> crear { get; set; }
        public Nullable<int> reportes { get; set; }
    
        public virtual CatEstado CatEstado { get; set; }
        public virtual TblModulo TblModulo { get; set; }
        public virtual TblSubModulo TblSubModulo { get; set; }
    }
}
