//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatPunto
    {
        public long idCatPuntos { get; set; }
        public Nullable<long> idSucursal { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> idTblUsuarioCrea { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatTipoUbicaciones { get; set; }
        public Nullable<long> codigoSucursalSigue { get; set; }
    
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatTipoUbicacione CatTipoUbicacione { get; set; }
        public virtual CatUbicacione CatUbicacione { get; set; }
    }
}
