//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatTiposRemesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatTiposRemesa()
        {
            this.CatRelationshipRemitentes = new HashSet<CatRelationshipRemitente>();
        }
    
        public long idCatTiposRemesas { get; set; }
        public string descripcion { get; set; }
        public string codigo { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> idTblUsuariosAltas { get; set; }
        public Nullable<System.DateTime> fechaHoraAlata { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaHoraModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatRelationshipRemitente> CatRelationshipRemitentes { get; set; }
    }
}
