//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatUbicacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatUbicacione()
        {
            this.TblCarteraCreditoes = new HashSet<TblCarteraCredito>();
            this.CatPuntos = new HashSet<CatPunto>();
            this.constanciasLaborales = new HashSet<constanciasLaborale>();
            this.TblAfiliaciones = new HashSet<TblAfiliacione>();
            this.TblAsignacionesEjecutivosSucursales = new HashSet<TblAsignacionesEjecutivosSucursale>();
            this.TblCertificacionesTecnicos = new HashSet<TblCertificacionesTecnico>();
            this.TblDestinos = new HashSet<TblDestino>();
            this.TblGruposAgencias = new HashSet<TblGruposAgencia>();
            this.TblMonitorGrabacions = new HashSet<TblMonitorGrabacion>();
            this.TblSucrusalesProductosCooitzas = new HashSet<TblSucrusalesProductosCooitza>();
        }
    
        public long idCatUbicaciones { get; set; }
        public Nullable<long> idCatTipoUbicaciones { get; set; }
        public Nullable<long> idCatRegiones { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string descripcion { get; set; }
        public string codigoNombre { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idCatUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatUsuarioModifica { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> idCatDepartamentosRepublicas { get; set; }
        public Nullable<long> idMunicipiosRepublicas { get; set; }
        public Nullable<long> idCatLugares { get; set; }
        public Nullable<decimal> captacionBase { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public string nombreTarjetaCredito { get; set; }
        public string isoUbicacionGrafica { get; set; }
        public Nullable<long> codigoSucrusalSigue { get; set; }
        public Nullable<long> idTblCaracterisitcasGrabacion { get; set; }
        public Nullable<long> codigoOrden { get; set; }
        public Nullable<decimal> totalAhorros { get; set; }
        public Nullable<decimal> plazoFijo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCarteraCredito> TblCarteraCreditoes { get; set; }
        public virtual CatDepartamentosRepublica CatDepartamentosRepublica { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatLugare CatLugare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatPunto> CatPuntos { get; set; }
        public virtual CatRegione CatRegione { get; set; }
        public virtual CatTipoUbicacione CatTipoUbicacione { get; set; }
        public virtual MunicipiosRepublica MunicipiosRepublica { get; set; }
        public virtual TblCaracterisitcasGrabacion TblCaracterisitcasGrabacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<constanciasLaborale> constanciasLaborales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAfiliacione> TblAfiliaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsignacionesEjecutivosSucursale> TblAsignacionesEjecutivosSucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCertificacionesTecnico> TblCertificacionesTecnicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDestino> TblDestinos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblGruposAgencia> TblGruposAgencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMonitorGrabacion> TblMonitorGrabacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSucrusalesProductosCooitza> TblSucrusalesProductosCooitzas { get; set; }
    }
}
