//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cc_Rubros
    {
        public long idTbl_Cc_Rubros { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string observacion { get; set; }
        public Nullable<long> idCatColaboradores { get; set; }
        public Nullable<long> idCatRubros { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idCatUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatUsuarioModifica { get; set; }
        public Nullable<long> idCatEstados { get; set; }
    
        public virtual CatColaboradore CatColaboradore { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatRubro CatRubro { get; set; }
    }
}
