//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_U_Roles
    {
        public long idTbl_U_Permisos { get; set; }
        public Nullable<long> idTblRoles { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> idTblUsuarioAsigna { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
    
        public virtual CatEstado CatEstado { get; set; }
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual TblRole TblRole { get; set; }
    }
}
