//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAfiliacione
    {
        public long idTblAfiliaciones { get; set; }
        public Nullable<long> codigoAsociado { get; set; }
        public string nombreCompleto { get; set; }
        public Nullable<long> idCatUbicaciones { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public string contratoVisa1 { get; set; }
        public string contratoVisa2 { get; set; }
        public string cartaBanco { get; set; }
        public string cartaCooperativa { get; set; }
        public string boletaPagoPos { get; set; }
        public Nullable<System.DateTime> fechaEnvioVisa { get; set; }
        public Nullable<System.DateTime> fechaRecepcionAfiliacion { get; set; }
        public string codigoAfiliacion { get; set; }
        public string idTerminal { get; set; }
        public string usuario { get; set; }
        public string contrasenia { get; set; }
        public Nullable<long> idEstadoZuma { get; set; }
        public string numeroCuentaAhorro { get; set; }
        public string numeroRecibo { get; set; }
        public Nullable<long> idCatZuma { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
    
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatUbicacione CatUbicacione { get; set; }
        public virtual CatZuma CatZuma { get; set; }
    }
}
