//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbitacorapremora
    {
        public long idtblbitacorapremora { get; set; }
        public Nullable<long> idtblpremora { get; set; }
        public Nullable<System.DateTime> fechayhorallamada { get; set; }
        public Nullable<long> idempleado { get; set; }
        public string observacion { get; set; }
        public Nullable<long> idcatestadoscallcenter { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual catestadoscallcenter catestadoscallcenter { get; set; }
        public virtual tblpremora tblpremora { get; set; }
    }
}
