//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBitacoraBusquedaUsuario
    {
        public long idTblBitacoraBusquedaUsuarios { get; set; }
        public Nullable<long> idTblUsuario { get; set; }
        public Nullable<System.DateTime> fechaHoraBusquedas { get; set; }
        public Nullable<long> idCatBusqueda { get; set; }
        public string noAsociado { get; set; }
        public string nombres { get; set; }
        public string dpi { get; set; }
        public Nullable<long> idCatEstados { get; set; }
    
        public virtual CatBusqueda CatBusqueda { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual TblUsuario TblUsuario { get; set; }
    }
}
