//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCarteraCredito
    {
        public long idTblCarteraCredito { get; set; }
        public Nullable<long> idCatUbicaciones { get; set; }
        public Nullable<long> cantidadCuentasSaldosQuetzales { get; set; }
        public Nullable<decimal> saldosQuetzales { get; set; }
        public Nullable<long> cantidadCuentasMoraQuetzales { get; set; }
        public Nullable<decimal> moraQuetzales { get; set; }
        public Nullable<decimal> saldosDolares { get; set; }
        public Nullable<decimal> moraDolares { get; set; }
        public Nullable<decimal> totalCartera { get; set; }
        public Nullable<long> totalCuentasMora { get; set; }
        public Nullable<decimal> totalMora { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idTblusuarioAlta { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatUbicacione CatUbicacione { get; set; }
    }
}
