//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCierresProducto
    {
        public long idTblCierresProductos { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<long> cantidad { get; set; }
        public Nullable<long> idCatMeses { get; set; }
        public Nullable<long> idCatAnios { get; set; }
        public Nullable<long> idTblProductosCooitza { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idUsuarioAlta { get; set; }
        public Nullable<long> idUsuarioModifica { get; set; }
        public Nullable<long> idCatEstados { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual TblUsuario TblUsuario1 { get; set; }
        public virtual CatAnio CatAnio { get; set; }
        public virtual CatMes CatMes { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual TblProductosCooitza TblProductosCooitza { get; set; }
    }
}
