//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCarteraCredito1
    {
        public long IdTblCarteraCredito { get; set; }
        public string Region { get; set; }
        public string Sucursal { get; set; }
        public string NombreCompleto { get; set; }
        public string NoAsociado { get; set; }
        public string Codigo { get; set; }
        public string TipoCredito { get; set; }
        public string Garantia { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaDesembolso { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string SubEstado { get; set; }
        public string MoraSubEstado { get; set; }
        public string DestinoDelCredito { get; set; }
        public string TipoAmortizacion { get; set; }
        public string ManejoCuotas { get; set; }
        public string CalculoInteres { get; set; }
        public string Frecuencia { get; set; }
        public Nullable<int> NumeroCuotas { get; set; }
        public Nullable<decimal> PorcentajeInteres { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<long> DiasMora { get; set; }
        public Nullable<long> CuotasMora { get; set; }
        public Nullable<System.DateTime> FechaSiguientePago { get; set; }
        public Nullable<System.DateTime> FechaUltimoPago { get; set; }
        public string TipoCartera { get; set; }
        public string Empleado { get; set; }
        public string Cartera { get; set; }
        public string SubCartera { get; set; }
        public string TipoSolicitud { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<long> IdTblUsuario { get; set; }
        public Nullable<long> IdTblUsuarioModifica { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> mes { get; set; }
        public Nullable<long> anio { get; set; }
    }
}
