//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDeclaracionSalud
    {
        public long idTblDeclaracionSalud { get; set; }
        public Nullable<long> Lg1 { get; set; }
        public Nullable<long> Lg2 { get; set; }
        public Nullable<long> Lg3 { get; set; }
        public Nullable<long> Lg4 { get; set; }
        public Nullable<long> Lg5 { get; set; }
        public Nullable<long> Lg6 { get; set; }
        public Nullable<long> Lg7 { get; set; }
        public Nullable<long> Lg8 { get; set; }
        public Nullable<long> Lg9 { get; set; }
        public Nullable<long> Lg10 { get; set; }
        public Nullable<long> Lg11 { get; set; }
        public Nullable<long> Lg12 { get; set; }
        public Nullable<long> Lg13 { get; set; }
        public Nullable<long> Lg14 { get; set; }
        public Nullable<long> Lg15 { get; set; }
        public Nullable<long> Lg16 { get; set; }
        public Nullable<long> Lg17 { get; set; }
        public Nullable<long> Lg18 { get; set; }
        public Nullable<long> Lg19 { get; set; }
        public Nullable<long> Lg20 { get; set; }
        public Nullable<long> Lg21 { get; set; }
        public Nullable<long> Lg22 { get; set; }
        public Nullable<long> Lg23 { get; set; }
        public Nullable<long> Lg24 { get; set; }
        public Nullable<long> Lg25 { get; set; }
        public Nullable<long> Lg26 { get; set; }
        public Nullable<long> Lg27 { get; set; }
        public Nullable<long> Lg28 { get; set; }
        public Nullable<long> Lg29 { get; set; }
        public Nullable<long> Lg30 { get; set; }
        public Nullable<long> Lg31 { get; set; }
        public Nullable<long> Lg32 { get; set; }
        public Nullable<long> Lg33 { get; set; }
        public Nullable<long> Lg34 { get; set; }
        public Nullable<long> Lg35 { get; set; }
        public Nullable<long> Lg36 { get; set; }
        public Nullable<long> Lg37 { get; set; }
        public Nullable<long> Lg38 { get; set; }
        public Nullable<long> Lg39 { get; set; }
        public Nullable<long> Lg40 { get; set; }
        public Nullable<long> Lg41 { get; set; }
        public Nullable<long> Lg42 { get; set; }
        public Nullable<long> Lg43 { get; set; }
        public Nullable<long> Lg44 { get; set; }
        public Nullable<long> Lg45 { get; set; }
        public Nullable<long> Lg46 { get; set; }
        public Nullable<long> Lg47 { get; set; }
        public Nullable<long> Lg48 { get; set; }
        public Nullable<long> Lg49 { get; set; }
        public Nullable<long> Lg50 { get; set; }
        public Nullable<long> Lg51 { get; set; }
        public Nullable<long> Lg52 { get; set; }
        public Nullable<long> Lg53 { get; set; }
        public string respuestaLg53 { get; set; }
        public Nullable<long> Lg54 { get; set; }
        public Nullable<long> Lg55 { get; set; }
        public Nullable<long> Lg56 { get; set; }
        public Nullable<long> Lg57 { get; set; }
        public string NombreMedicina { get; set; }
        public string Dosis { get; set; }
        public string RazonMedicina { get; set; }
        public string TiempoMedicina { get; set; }
        public string MedicinaReceta { get; set; }
        public string NombrePerInfoSalud { get; set; }
        public string NumeroPregunta { get; set; }
        public string NombreEnfermedad { get; set; }
        public string DuracionEnfermedad { get; set; }
        public Nullable<int> Mess { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public string NombresDirMedicos { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn1 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn2 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn3 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn4 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn5 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn6 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn7 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn8 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn9 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn10 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn11 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn12 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn13 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn14 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn15 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn16 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn17 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn18 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn19 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn20 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn21 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn22 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn23 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn24 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn25 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn26 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn27 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn28 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn29 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn30 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn31 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn32 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn33 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn34 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn35 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn36 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn37 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn38 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn39 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn40 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn41 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn42 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn43 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn44 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn45 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn46 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn47 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn48 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn49 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn50 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn51 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn52 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn53 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn54 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn55 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn56 { get; set; }
        public virtual CatEstado CatEstado { get; set; }
    }
}
