//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDeclaracionSaludlg
    {
        public long idTblDeclaracionSaludlg { get; set; }
        public string lg1 { get; set; }
        public string lg2 { get; set; }
        public string lg3 { get; set; }
        public string lg4 { get; set; }
        public string lg5 { get; set; }
        public string lg6 { get; set; }
        public string lg7 { get; set; }
        public string lg8 { get; set; }
        public string lg9 { get; set; }
        public Nullable<long> lg10 { get; set; }
        public Nullable<long> lg11 { get; set; }
        public Nullable<long> lg12 { get; set; }
        public Nullable<long> lg13 { get; set; }
        public Nullable<long> lg14 { get; set; }
        public Nullable<long> lg15 { get; set; }
        public Nullable<long> lg16 { get; set; }
        public Nullable<long> lg17 { get; set; }
        public Nullable<long> lg18 { get; set; }
        public Nullable<long> lg19 { get; set; }
        public Nullable<long> lg20 { get; set; }
        public Nullable<long> lg21 { get; set; }
        public Nullable<long> lg22 { get; set; }
        public Nullable<long> lg23 { get; set; }
        public Nullable<long> lg24 { get; set; }
        public Nullable<long> lg25 { get; set; }
        public Nullable<long> lg26 { get; set; }
        public Nullable<long> lg27 { get; set; }
        public Nullable<long> lg28 { get; set; }
        public Nullable<long> lg29 { get; set; }
        public Nullable<long> lg30 { get; set; }
        public Nullable<long> lg31 { get; set; }
        public Nullable<long> lg32 { get; set; }
        public Nullable<long> lg33 { get; set; }
        public Nullable<long> lg34 { get; set; }
        public Nullable<long> lg35 { get; set; }
        public Nullable<long> lg36 { get; set; }
        public Nullable<long> lg37 { get; set; }
        public Nullable<long> lg38 { get; set; }
        public Nullable<long> lg39 { get; set; }
        public Nullable<long> lg40 { get; set; }
        public Nullable<long> lg41 { get; set; }
        public Nullable<long> lg42 { get; set; }
        public Nullable<long> lg43 { get; set; }
        public Nullable<long> lg44 { get; set; }
        public Nullable<long> lg45 { get; set; }
        public Nullable<long> lg46 { get; set; }
        public Nullable<long> lg47 { get; set; }
        public Nullable<long> lg48 { get; set; }
        public Nullable<long> lg49 { get; set; }
        public Nullable<long> lg50 { get; set; }
        public Nullable<long> lg51 { get; set; }
        public Nullable<long> lg52 { get; set; }
        public Nullable<long> lg53 { get; set; }
        public Nullable<long> lg54 { get; set; }
        public Nullable<long> lg55 { get; set; }
        public Nullable<long> lg56 { get; set; }
        public Nullable<long> lg57 { get; set; }
        public Nullable<long> lg58 { get; set; }
        public Nullable<long> lg59 { get; set; }
        public Nullable<long> lg60 { get; set; }
        public Nullable<long> lg61 { get; set; }
        public Nullable<long> lg62 { get; set; }
        public Nullable<long> lg63 { get; set; }
        public Nullable<long> lg64 { get; set; }
        public string lg65 { get; set; }
        public string lg66 { get; set; }
        public string lg67 { get; set; }
        public string lg68 { get; set; }
        public string lg69 { get; set; }
        public string lg70 { get; set; }
        public string lg71 { get; set; }
        public string lg72 { get; set; }
        public string lg73 { get; set; }
        public string lg74 { get; set; }
        public string lg75 { get; set; }
        public string lg76 { get; set; }
        public string lg77 { get; set; }
        public string lg78 { get; set; }
        public string lg79 { get; set; }
        public string lg80 { get; set; }
        public string lg81 { get; set; }
        public string lg82 { get; set; }
        public string lg83 { get; set; }
        public string lg84 { get; set; }
        public string lg85 { get; set; }
        public string lg86 { get; set; }
        public string lg87 { get; set; }
        public string lg88 { get; set; }
        public string lg89 { get; set; }
        public string lg90 { get; set; }
        public string lg91 { get; set; }
        public string lg92 { get; set; }
        public string lg93 { get; set; }
        public string lg94 { get; set; }
        public string lg95 { get; set; }
        public string lg96 { get; set; }
        public string lg97 { get; set; }
        public string lg98 { get; set; }
        public string lg99 { get; set; }
        public string lg100 { get; set; }
        public string lg101 { get; set; }
        public string lg102 { get; set; }
        public string lg103 { get; set; }
        public string lg104 { get; set; }
        public string lg105 { get; set; }
        public string lg106 { get; set; }
        public string lg107 { get; set; }
        public string lg108 { get; set; }
        public string lg109 { get; set; }
        public string lg110 { get; set; }
        public string lg111 { get; set; }
        public string lg112 { get; set; }
        public string lg113 { get; set; }
        public string lg114 { get; set; }
        public string lg115 { get; set; }
        public string lg116 { get; set; }
        public string lg117 { get; set; }
        public string lg118 { get; set; }
        public string lg119 { get; set; }
        public string lg120 { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
    
        public virtual CatOpcionesChn CatOpcionesChn { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn1 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn2 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn3 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn4 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn5 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn6 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn7 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn8 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn9 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn10 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn11 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn12 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn13 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn14 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn15 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn16 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn17 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn18 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn19 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn20 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn21 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn22 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn23 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn24 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn25 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn26 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn27 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn28 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn29 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn30 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn31 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn32 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn33 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn34 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn35 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn36 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn37 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn38 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn39 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn40 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn41 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn42 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn43 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn44 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn45 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn46 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn47 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn48 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn49 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn50 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn51 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn52 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn53 { get; set; }
        public virtual CatOpcionesChn CatOpcionesChn54 { get; set; }
    }
}
