//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDeposito
    {
        public long idTblDepositos { get; set; }
        public Nullable<long> idTblSolicitudes { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaDeposito { get; set; }
        public string noBoleta { get; set; }
        public string noCuenta { get; set; }
        public string imagenComprobanteDeposito { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<long> idCatEstadosViaticos { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
        public Nullable<long> idCatEstados { get; set; }
    
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatEstadosViatico CatEstadosViatico { get; set; }
    }
}
