//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDeclaracionConcentimientolg
    {
        public long idTblDeclaracionConcentimientolg { get; set; }
        public string lg1 { get; set; }
        public string lg2 { get; set; }
        public string lg3 { get; set; }
        public string lg4 { get; set; }
        public string lg5 { get; set; }
        public string lg6 { get; set; }
        public string lg7 { get; set; }
        public string lg8 { get; set; }
        public string lg9 { get; set; }
        public string lg10 { get; set; }
        public string lg11 { get; set; }
        public string lg12 { get; set; }
        public string lg13 { get; set; }
        public string lg14 { get; set; }
        public string lg15 { get; set; }
        public string lg16 { get; set; }
        public string lg17 { get; set; }
        public string lg18 { get; set; }
        public string lg19 { get; set; }
        public string lg20 { get; set; }
        public string lg21 { get; set; }
        public Nullable<long> lg22 { get; set; }
        public string lg23 { get; set; }
        public string lg24 { get; set; }
        public string lg25 { get; set; }
        public string lg26 { get; set; }
        public string lg27 { get; set; }
        public Nullable<long> lg28 { get; set; }
        public string lg29 { get; set; }
        public string lg30 { get; set; }
        public string lg31 { get; set; }
        public string lg32 { get; set; }
        public string lg33 { get; set; }
        public string lg34 { get; set; }
        public Nullable<long> lg35 { get; set; }
        public string lg36 { get; set; }
        public string lg37 { get; set; }
        public string lg38 { get; set; }
        public string lg39 { get; set; }
        public string lg40 { get; set; }
        public Nullable<long> lg41 { get; set; }
        public string lg42 { get; set; }
        public string lg43 { get; set; }
        public string lg44 { get; set; }
        public string lg45 { get; set; }
        public string lg46 { get; set; }
        public string lg47 { get; set; }
        public string lg48 { get; set; }
        public string lg49 { get; set; }
        public string lg50 { get; set; }
        public string lg51 { get; set; }
        public string lg52 { get; set; }
        public string lg53 { get; set; }
        public string lg54 { get; set; }
        public string lg55 { get; set; }
        public string lg56 { get; set; }
        public string lg57 { get; set; }
        public string lg58 { get; set; }
        public string lg59 { get; set; }
        public string lg60 { get; set; }
        public string lg61 { get; set; }
        public string lg62 { get; set; }
        public string lg63 { get; set; }
        public string lg64 { get; set; }
        public string lg65 { get; set; }
        public string lg66 { get; set; }
        public string lg67 { get; set; }
        public string lg68 { get; set; }
        public string lg69 { get; set; }
        public string lg70 { get; set; }
        public string lg71 { get; set; }
        public string lg72 { get; set; }
        public string lg73 { get; set; }
        public string lg74 { get; set; }
        public string lg75 { get; set; }
        public string lg76 { get; set; }
        public string lg77 { get; set; }
        public string lg78 { get; set; }
        public string lg79 { get; set; }
        public string lg80 { get; set; }
        public string lg81 { get; set; }
        public string lg82 { get; set; }
        public string lg83 { get; set; }
        public string lg84 { get; set; }
        public string lg85 { get; set; }
        public string lg86 { get; set; }
        public string lg87 { get; set; }
        public string lg88 { get; set; }
        public string lg89 { get; set; }
        public string lg90 { get; set; }
        public string lg91 { get; set; }
        public string lg92 { get; set; }
        public string lg93 { get; set; }
        public string lg94 { get; set; }
        public string lg95 { get; set; }
        public string lg96 { get; set; }
        public string lg97 { get; set; }
        public string lg98 { get; set; }
        public string lg99 { get; set; }
        public string lg100 { get; set; }
        public string lg101 { get; set; }
        public string lg102 { get; set; }
        public string lg103 { get; set; }
        public string lg104 { get; set; }
        public string lg105 { get; set; }
        public string lg106 { get; set; }
        public string lg107 { get; set; }
        public string lg108 { get; set; }
        public string lg109 { get; set; }
        public string lg110 { get; set; }
        public string lg111 { get; set; }
        public string lg112 { get; set; }
        public string lg113 { get; set; }
        public string lg114 { get; set; }
        public string lg115 { get; set; }
        public string lg116 { get; set; }
        public string lg117 { get; set; }
        public string lg118 { get; set; }
        public string lg119 { get; set; }
        public string lg120 { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> lg121 { get; set; }
        public Nullable<long> lg122 { get; set; }
        public Nullable<long> lg123 { get; set; }
        public Nullable<long> lg128 { get; set; }
        public Nullable<long> lg127 { get; set; }
        public Nullable<long> lg126 { get; set; }
        public Nullable<long> lg125 { get; set; }
        public Nullable<long> lg124 { get; set; }
        public Nullable<long> idCatTipoAfiliacion { get; set; }
    
        public virtual CatParentesco CatParentesco { get; set; }
        public virtual CatParentesco CatParentesco1 { get; set; }
        public virtual CatParentesco CatParentesco2 { get; set; }
        public virtual CatParentesco CatParentesco3 { get; set; }
        public virtual CatParentescosGastosM CatParentescosGastosM { get; set; }
        public virtual CatParentescosGastosM CatParentescosGastosM1 { get; set; }
        public virtual CatParentescosGastosM CatParentescosGastosM2 { get; set; }
        public virtual CatParentescosGastosM CatParentescosGastosM3 { get; set; }
        public virtual CatTiposDocumento CatTiposDocumento { get; set; }
        public virtual CatTiposDocumento CatTiposDocumento1 { get; set; }
        public virtual CatTiposDocumento CatTiposDocumento2 { get; set; }
        public virtual CatTiposDocumento CatTiposDocumento3 { get; set; }
    }
}
