//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEntrega
    {
        public long idTblEntregas { get; set; }
        public Nullable<long> idAgencia { get; set; }
        public string numeroAsociado { get; set; }
        public Nullable<long> idTblUsuario { get; set; }
        public Nullable<long> idCatOpciones { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string agencia { get; set; }
        public Nullable<long> idCatEstadosAsociado { get; set; }
        public Nullable<long> idCatPromociones { get; set; }
        public Nullable<System.DateTime> fechaSorteo { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual CatPromocione CatPromocione { get; set; }
    }
}
