//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFacturasXcatRubro
    {
        public long idTblFacturasXcatRubros { get; set; }
        public Nullable<long> idCatRubros { get; set; }
        public Nullable<long> idTblFacturas { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idCatUsuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public string detalle { get; set; }
    
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatRubro CatRubro { get; set; }
        public virtual TblFactura TblFactura { get; set; }
    }
}
