//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGruposAgencia
    {
        public long idTblGruposAgencias { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<long> idCatUbicaciones { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<long> idTblUsuariosAltas { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual TblUsuario TblUsuario1 { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatUbicacione CatUbicacione { get; set; }
    }
}
