//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHistoriale
    {
        public long idTblHistoriales { get; set; }
        public Nullable<long> idTblModulos { get; set; }
        public Nullable<long> idTblSubModulos { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaConsulta { get; set; }
        public string contenidoConsultado { get; set; }
    }
}
