//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHorario
    {
        public long idTblHorarios { get; set; }
        public int horaInicio { get; set; }
        public int horaFin { get; set; }
        public int minutosFin { get; set; }
        public int segundosFin { get; set; }
        public string sistema { get; set; }
        public int horaInicio2 { get; set; }
        public int horaFin2 { get; set; }
        public int minutosFin2 { get; set; }
        public int segundosFin2 { get; set; }
        public int horaInicio3 { get; set; }
        public int horaFin3 { get; set; }
        public int minutosFin3 { get; set; }
        public int segundosFin3 { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    }
}
