//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHistorico
    {
        public long idTblHistoricos { get; set; }
        public string fechadelatransaccion { get; set; }
        public string tipocliente { get; set; }
        public string tipodeidentificaciondelcliente { get; set; }
        public string nodeordendelacedula { get; set; }
        public string numerodeidentificaciondelcliente { get; set; }
        public string primerapellido { get; set; }
        public string segundoapellido { get; set; }
        public string apellidodecasada { get; set; }
        public string primernombre { get; set; }
        public string segundonombre { get; set; }
        public string tercernombre { get; set; }
        public string fechadenacimientodelcliente { get; set; }
        public string paisdenacionalidaddelcliente { get; set; }
        public string numerodecuenta { get; set; }
        public string tipodetransaccion { get; set; }
        public string tipodemoneda { get; set; }
        public string montoenmonedaoriginal { get; set; }
        public string montoenusdolares { get; set; }
        public string localidaddelatransaccion { get; set; }
        public Nullable<long> idTblPeriodos { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idCatUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatUsuarioModifica { get; set; }
        public Nullable<long> idCatEstados { get; set; }
    
        public virtual CatEstado CatEstado { get; set; }
        public virtual TblPeriodo TblPeriodo { get; set; }
    }
}
