//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLogCatalogosRch1
    {
        public long idTblLogCatalogosRch { get; set; }
        public string jsonRequest { get; set; }
        public string jsonResponse { get; set; }
        public Nullable<long> idCooperativa { get; set; }
        public Nullable<System.DateTime> fechaHoraConsulta { get; set; }
        public Nullable<long> idCatEstados { get; set; }
    }
}
