//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMonitorGrabacion
    {
        public long idTblMonitorGrabacion { get; set; }
        public Nullable<long> idCatUbicaciones { get; set; }
        public Nullable<int> cantidadCamarasFuncionando { get; set; }
        public string capturaPatalla { get; set; }
        public Nullable<long> dvrFuncionando { get; set; }
        public Nullable<long> sucursalTieneInternet { get; set; }
        public Nullable<long> dvrGrabando { get; set; }
        public string comentario { get; set; }
        public long idCatEstados { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<int> numeroCertificacionDia { get; set; }
        public Nullable<long> errorDeCamaras { get; set; }
        public Nullable<int> cantidadCamarasError { get; set; }
        public string detalleCamaras { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<long> horarioDiferencia { get; set; }
        public string idDiferenciaTiempo { get; set; }
        public Nullable<long> diferenciaHoras { get; set; }
        public Nullable<long> diferenciaMinutos { get; set; }
        public Nullable<long> idCatEstadosTiempo { get; set; }
        public Nullable<long> totalDiasGrabando { get; set; }
        public Nullable<long> totalDeInconsistencias { get; set; }
        public Nullable<long> presentaInconsistencias { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatEstado CatEstado1 { get; set; }
        public virtual CatEstadosTiempo CatEstadosTiempo { get; set; }
        public virtual CatOpcione CatOpcione { get; set; }
        public virtual CatUbicacione CatUbicacione { get; set; }
    }
}
