//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMigracion
    {
        public long idTblMigracion { get; set; }
        public string lg1 { get; set; }
        public string lg2 { get; set; }
        public string lg3 { get; set; }
        public string lg4 { get; set; }
        public string lg5 { get; set; }
        public string lg6 { get; set; }
        public string lg7 { get; set; }
        public string lg8 { get; set; }
        public string lg9 { get; set; }
        public string lg10 { get; set; }
        public string lg11 { get; set; }
        public string lg12 { get; set; }
        public string lg13 { get; set; }
        public string lg14 { get; set; }
        public string lg15 { get; set; }
        public string lg16 { get; set; }
        public string lg17 { get; set; }
        public string lg18 { get; set; }
        public string lg19 { get; set; }
        public string lg20 { get; set; }
        public string lg21 { get; set; }
        public string lg22 { get; set; }
        public string lg23 { get; set; }
        public string lg24 { get; set; }
        public string lg25 { get; set; }
        public string lg26 { get; set; }
        public string lg27 { get; set; }
        public string lg28 { get; set; }
        public string lg29 { get; set; }
        public string lg30 { get; set; }
        public string lg31 { get; set; }
        public string lg32 { get; set; }
        public string lg33 { get; set; }
        public string lg34 { get; set; }
        public string lg35 { get; set; }
        public string lg36 { get; set; }
        public string lg37 { get; set; }
        public string lg38 { get; set; }
        public string lg39 { get; set; }
        public string lg40 { get; set; }
        public string lg41 { get; set; }
        public string lg42 { get; set; }
        public string lg43 { get; set; }
        public string lg44 { get; set; }
        public string lg45 { get; set; }
        public string lg46 { get; set; }
        public string lg47 { get; set; }
        public string lg48 { get; set; }
        public string lg49 { get; set; }
        public string lg50 { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual TblUsuario TblUsuario1 { get; set; }
        public virtual CatEstado CatEstado { get; set; }
    }
}
