//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpremora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblpremora()
        {
            this.tblbitacorapremoras = new HashSet<tblbitacorapremora>();
        }
    
        public long idtblpremora { get; set; }
        public Nullable<long> cuenta { get; set; }
        public string nombre { get; set; }
        public Nullable<long> telefono { get; set; }
        public Nullable<decimal> minimo { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<decimal> visacuota { get; set; }
        public Nullable<long> dpi { get; set; }
        public string agencia { get; set; }
        public Nullable<long> idagencia { get; set; }
        public Nullable<long> idempleado { get; set; }
        public Nullable<System.DateTime> fechaingreso { get; set; }
        public Nullable<long> idcatestados { get; set; }
        public Nullable<long> idcatestadoscallcenter { get; set; }
        public Nullable<System.DateTime> fechaactualizacion { get; set; }
        public Nullable<long> idempleadoactualiza { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual TblUsuario TblUsuario1 { get; set; }
        public virtual catestadoscallcenter catestadoscallcenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbitacorapremora> tblbitacorapremoras { get; set; }
        public virtual CatEstado CatEstado { get; set; }
    }
}
