//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductosCooitza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProductosCooitza()
        {
            this.TblAsignaciones = new HashSet<TblAsignacione>();
            this.TblCierresProductos = new HashSet<TblCierresProducto>();
            this.TblEmpleadosMetas = new HashSet<TblEmpleadosMeta>();
            this.TblSucrusalesProductosCooitzas = new HashSet<TblSucrusalesProductosCooitza>();
        }
    
        public long idTblProductosCooitza { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> idCatTipificacionProductos { get; set; }
        public Nullable<long> idCore { get; set; }
        public Nullable<decimal> saldoCierre { get; set; }
        public Nullable<long> cantidadCierre { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idTblUsuariosAlta { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
        public Nullable<long> idCatTiposMedicion { get; set; }
        public string expresionRegular { get; set; }
        public Nullable<long> idCatTiposOperacion { get; set; }
        public Nullable<long> idCatTiposConsultas { get; set; }
        public Nullable<long> idCatTiposFiltrosEvaluaciones { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual TblUsuario TblUsuario1 { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatTipificacionProducto CatTipificacionProducto { get; set; }
        public virtual CatTiposConsulta CatTiposConsulta { get; set; }
        public virtual CatTiposFiltrosEvaluacione CatTiposFiltrosEvaluacione { get; set; }
        public virtual CatTiposMedicion CatTiposMedicion { get; set; }
        public virtual CatTiposOperacion CatTiposOperacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAsignacione> TblAsignaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCierresProducto> TblCierresProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpleadosMeta> TblEmpleadosMetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSucrusalesProductosCooitza> TblSucrusalesProductosCooitzas { get; set; }
    }
}
