//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSolicitudesMovimientosDetalle
    {
        public long idTblSolicitudesMovimientosDetalle { get; set; }
        public Nullable<long> idTblSolicitudesMovimientos { get; set; }
        public Nullable<long> idCatTiposMovimientos { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> idCatTiposMonedas { get; set; }
        public Nullable<long> idTblUsuariosAltas { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<long> idTblUsuariosModifica { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public string archivo { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatTiposMoneda CatTiposMoneda { get; set; }
        public virtual CatTiposMovimiento CatTiposMovimiento { get; set; }
        public virtual TblSolicitudesMoviemiento TblSolicitudesMoviemiento { get; set; }
    }
}
