//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSolicitudesMoviemiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSolicitudesMoviemiento()
        {
            this.TblSolicitudesMovimientosDetalles = new HashSet<TblSolicitudesMovimientosDetalle>();
        }
    
        public long idTblSolicitudesMoviemientos { get; set; }
        public Nullable<long> idTblSolicitudesCooitzas { get; set; }
        public Nullable<long> idCatProveedorPrincipal { get; set; }
        public Nullable<long> idCatEstadoSolicitudes { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<long> idTblUsuariosAlta { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<long> idTblUsuariosModifica { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> idCatProveedorSegundo { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatEstadoSolicitude CatEstadoSolicitude { get; set; }
        public virtual CatProveedoresExterno CatProveedoresExterno { get; set; }
        public virtual CatProveedoresExterno CatProveedoresExterno1 { get; set; }
        public virtual TblSolicitudesCooitza TblSolicitudesCooitza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudesMovimientosDetalle> TblSolicitudesMovimientosDetalles { get; set; }
    }
}
