//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSolicitude
    {
        public long idTblSolicitudes { get; set; }
        public Nullable<long> idCatTipoSolicitudes { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public string nombreSolicitud { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<long> idCatOpciones { get; set; }
        public Nullable<long> idCatTipoAnticipo { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatUsuarioModifica { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> idEstadoProceso { get; set; }
        public string detalleEstado { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual TblUsuario TblUsuario1 { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatEstadosViatico CatEstadosViatico { get; set; }
        public virtual CatTipoAnticipo CatTipoAnticipo { get; set; }
        public virtual CatTipoSolicitude CatTipoSolicitude { get; set; }
    }
}
