//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSubModulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSubModulo()
        {
            this.CatPermisos = new HashSet<CatPermiso>();
            this.TblPermisosUsuarios = new HashSet<TblPermisosUsuario>();
            this.TblBitacoraServices = new HashSet<TblBitacoraService>();
            this.TblHistoriales1 = new HashSet<TblHistoriales1>();
        }
    
        public long idTblSubModulos { get; set; }
        public Nullable<long> idTblModulos { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public string icono { get; set; }
        public string controlador { get; set; }
        public string accion { get; set; }
        public string titulo { get; set; }
        public Nullable<int> ordenar { get; set; }
        public Nullable<long> idCatIconos { get; set; }
        public string varios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatPermiso> CatPermisos { get; set; }
        public virtual TblModulo TblModulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPermisosUsuario> TblPermisosUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBitacoraService> TblBitacoraServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHistoriales1> TblHistoriales1 { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatIcono CatIcono { get; set; }
        public virtual TblUsuario TblUsuario { get; set; }
    }
}
