//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSucrusalesProductosCooitza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblSucrusalesProductosCooitza()
        {
            this.TblEmpleadosMetas = new HashSet<TblEmpleadosMeta>();
        }
    
        public long idTblSucrusalesProductosCooitza { get; set; }
        public long idCatUbicaciones { get; set; }
        public long idTblProductosCooitza { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public long cantidad { get; set; }
        public Nullable<decimal> metasAnual { get; set; }
        public long cantidadMetaAnual { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idTblUsuariosAlta { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatAnios { get; set; }
        public Nullable<long> idCatMeses { get; set; }
        public Nullable<long> cantidadMetaMensual { get; set; }
        public Nullable<decimal> metasMensual { get; set; }
        public Nullable<long> idTblAsignaciones { get; set; }
        public Nullable<long> idTblUsuarioModifica { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual TblUsuario TblUsuario1 { get; set; }
        public virtual CatAnio CatAnio { get; set; }
        public virtual CatMes CatMes { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatUbicacione CatUbicacione { get; set; }
        public virtual TblAsignacione TblAsignacione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpleadosMeta> TblEmpleadosMetas { get; set; }
        public virtual TblProductosCooitza TblProductosCooitza { get; set; }
    }
}
