//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSiguePagar
    {
        public long idTblSiguePagar { get; set; }
        public string FechaNacimiento { get; set; }
        public string FechaExpiraId { get; set; }
        public string GastosMensuales { get; set; }
        public string IngresosMensuales { get; set; }
        public string CantidadRemesaMensual { get; set; }
        public string MontoRemesasMensual { get; set; }
        public string Direccion { get; set; }
        public string PaisNacimientoIdentificacionISO3 { get; set; }
        public string EstadoNacimiento { get; set; }
        public string Colonia { get; set; }
        public string CiudadResidencia { get; set; }
        public string Identificacion1 { get; set; }
        public string Identificacion2 { get; set; }
        public string Email { get; set; }
        public string Genero { get; set; }
        public string LugarEmisionId { get; set; }
        public string EstadoCivil { get; set; }
        public string TipoId { get; set; }
        public string NumeroId { get; set; }
        public string ApellidoCasada { get; set; }
        public string PaisISO3 { get; set; }
        public string NacionalidadISO3 { get; set; }
        public string Ocupacion { get; set; }
        public string Telefono { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string TercerNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string LugarNacimiento { get; set; }
        public string FinalidadFondos { get; set; }
        public string RelacionRemitente { get; set; }
        public string CiudadRecidencia { get; set; }
        public string PaisResidenciaISO3 { get; set; }
        public string EstadoResidencia { get; set; }
        public string NombreConyugue { get; set; }
        public string NumeroNit { get; set; }
        public string ZipCode { get; set; }
        public string CodigoOficinaPago { get; set; }
        public string NumeroRecibo { get; set; }
        public string NumeroRemesa { get; set; }
        public Nullable<System.DateTime> fechaHoraPago { get; set; }
        public string numeroDeCuenta { get; set; }
        public string fechaNacimientoBenTransac { get; set; }
        public string jsonRequestPago { get; set; }
        public string jsonEnviado { get; set; }
        public string httpStatusCodePago { get; set; }
        public string jsonResponsePago { get; set; }
        public string usuarioTransac { get; set; }
        public Nullable<long> idTblSigueTransac { get; set; }
        public Nullable<long> esAsociado { get; set; }
        public Nullable<long> idCatEstatusTransac { get; set; }
        public string codigoAsociado { get; set; }
        public string codigoCliente { get; set; }
        public string xmlRequest { get; set; }
        public string xmlResponse { get; set; }
    
        public virtual CatEstatusTransac CatEstatusTransac { get; set; }
        public virtual TblSigueTransac TblSigueTransac { get; set; }
    }
}
