//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSmsCore
    {
        public long idTblSmsCore { get; set; }
        public string mensaje { get; set; }
        public string segmento { get; set; }
        public Nullable<System.DateTime> fechaHoraRegistro { get; set; }
        public string resultadoMensaje { get; set; }
        public string llave { get; set; }
        public string telefono { get; set; }
    }
}
