//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransUnionTest
    {
        public long idTblTransUnionTest { get; set; }
        public string jsonRequest { get; set; }
        public Nullable<System.DateTime> fechaBusqueda { get; set; }
        public string usuario { get; set; }
        public string respuesta { get; set; }
        public string codigoRespuesta { get; set; }
        public string score { get; set; }
        public string usuarioProcessTransac { get; set; }
        public string nombreCompleto { get; set; }
        public string identificacion { get; set; }
        public string fechaNacimiento { get; set; }
    }
}
