//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuarios1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUsuarios1()
        {
            this.CatTblUsuariosXTblSistemas = new HashSet<CatTblUsuariosXTblSistema>();
            this.CatEstadosViaticos = new HashSet<CatEstadosViatico>();
            this.CatOpcionesVehiculos = new HashSet<CatOpcionesVehiculo>();
        }
    
        public long idTblUsuarios { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string tercerNombre { get; set; }
        public string cuartoNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string apellidoCasada { get; set; }
        public Nullable<long> idCatSexo { get; set; }
        public Nullable<long> idCatEstadoCivil { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public Nullable<long> dpi { get; set; }
        public Nullable<long> numeroPasaporte { get; set; }
        public string nit { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public string correoelectronico { get; set; }
        public Nullable<long> idCatUbicaciones { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idCatUsuarios { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatUsuarioModifica { get; set; }
    
        public virtual CatEstadoCivil CatEstadoCivil { get; set; }
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatSexo CatSexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatTblUsuariosXTblSistema> CatTblUsuariosXTblSistemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatEstadosViatico> CatEstadosViaticos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatOpcionesVehiculo> CatOpcionesVehiculos { get; set; }
    }
}
