//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuarios_Coordinador
    {
        public long idTblUsuarios_Coordinador { get; set; }
        public Nullable<long> idTblUsuario_jefe { get; set; }
        public Nullable<long> idTblUsuario_subAlterno { get; set; }
        public Nullable<long> idTblUsuario_crea { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<long> idTblUsuario_modifica { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<long> idCatEstados { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual TblUsuario TblUsuario1 { get; set; }
        public virtual TblUsuario TblUsuario2 { get; set; }
        public virtual TblUsuario TblUsuario3 { get; set; }
        public virtual CatEstado CatEstado { get; set; }
    }
}
