//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redchapinapayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblVehiculo()
        {
            this.TblSolicitudesXtblVehiculos = new HashSet<TblSolicitudesXtblVehiculo>();
        }
    
        public long idTblVehiculos { get; set; }
        public Nullable<long> idCatOpcionesVehiculos { get; set; }
        public Nullable<long> idTblUsuarios { get; set; }
        public string nombrePropietario { get; set; }
        public Nullable<int> nitPropietario { get; set; }
        public Nullable<long> idCatTipoPlacas { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string color { get; set; }
        public string imagenVehiculo { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
        public Nullable<long> idCatUsuarioModifica { get; set; }
        public Nullable<long> idCatEstados { get; set; }
        public string noPlaca { get; set; }
        public Nullable<decimal> kilometraje { get; set; }
        public string imagenOdometro { get; set; }
        public Nullable<System.DateTime> fechaProximoServicio { get; set; }
        public string observaciones { get; set; }
        public string tallerAsignado { get; set; }
        public string tipoVehiculo { get; set; }
        public string linea { get; set; }
    
        public virtual CatEstado CatEstado { get; set; }
        public virtual CatOpcionesVehiculo CatOpcionesVehiculo { get; set; }
        public virtual CatTipoPlaca CatTipoPlaca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSolicitudesXtblVehiculo> TblSolicitudesXtblVehiculos { get; set; }
    }
}
